#!/bin/sh

occt_resources=/usr/share/foamairplanestudio/occt/resources
export CSF_OCCTResourcePath="$occt_resources"
export CSF_MDTVTexturesDirectory="$occt_resources/Textures"
export CSF_ShadersDirectory="$occt_resources/Shaders"
export CSF_SHMessage="$occt_resources/SHMessage"
export LD_LIBRARY_PATH="/usr/lib/foamairplanestudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

exec /usr/lib/foamairplanestudio/foamairplanestudio "$@"
